from protocols.utils import *

VPN_SERVER_IP = "localhost"
VPN_SERVER_PORT = 8080

REQUEST_SEPARATOR = ";"
REQUEST_LOGIN_HEADER = "l"
REQUEST_ACCEPTED_HEADER = "a"
REQUEST_ERROR_HEADER = "e"
REQUEST_PACKAGE_HEADER = "p"
REQUEST_RESPONSE_HEADER = "r"
